### ISSUE TITLE
NerdPack: package availability based on unRAID version 

### ISSUE THREAD

**Issue by eschultz** [dmacias72/unRAID-plugins#7]
Just adding this issue as a FYI.  Some of the package versions currently in NerdPack are not compatible with unRAID 6.2.  There are newer package versions available but a couple of them won't work with unRAID 6.1.x.

Maybe specify a `min_version` and/or `max_version` on certain packages in packages.json?:

``` json
[
    {
        "name": "apr-1.5.0-x86_64-1.txz",
        "max_version": "6.1.99",
        "......"
    },
    {
        "name": "apr-1.5.2-x86_64-1.txz",
        "min_version": "6.2",
        "......"
    }
]
```

Meaning:
- Using unRAID 6.1.7 or older and you only see `apr-1.5.0-x86_64-1.txz`
- Using unRAID 6.2 or newer and you only see `apr-1.5.2-x86_64-1.txz`

PHP has a pretty useful [version_compare](http://php.net/manual/en/function.version-compare.php) function to help out comparing the min/max_version with what's in `/etc/unraid-version`

**Comment by dmacias72** [comment]
Thanks for the heads up. How much time do I have :)

**Comment by dmacias72** [comment]
I ended up setting up separate github repos for 6.1 and 6.2
